server.port = 9000

spring.security.user.name=natalie
spring.security.user.password=9fd9cde2-2da5-4841-83d6-0dad6c907f01

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=lumosmaxima
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.SQL=trace
logging.level.org.hibernate.orm.jdbc.bind=trace







